apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrelease.yaml
- imagepolicy.yaml
- imageupdateautomation.yaml
secretGenerator:
- name: podinfo-values
  files:
  - values.yaml=values.enc.yaml
configurations:
- kustomizeconfig.yaml
