ui:
  message: ENC[AES256_GCM,data:tvpLl5ZCqCJBtk7fvryq3w==,iv:d3l7h+y7uLMV8QPIpoYlxjdaUn5NiIxquv43KDuUNLY=,tag:mnJpaVxxnjiH40jNuXrTFQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2022-10-12T22:44:12Z"
  mac: ENC[AES256_GCM,data:u1k960pSiDfI5OnlY2QJIxssBA0c/hHDFZ+d/AtKNOQd9sAP33/fowroCPx9edIGH1gDU5AOVQ2rsW2n19tfrk2n3lo7R6JyP05DKcEprzAj+waI+vP0ZI0PbKNgbx7rtRvayFgCqAe4wcAkysPrxtSj7HYm2k9+5ksYl80eVHk=,iv:5LC58DZ2np4sV08zVfZF46BNeere37FedHT4qZEC//E=,tag:mIast0C4CXgvJVJdr1BccQ==,type:str]
  pgp:
  - created_at: "2022-10-12T08:45:17Z"
    enc: |
      -----BEGIN PGP MESSAGE-----

      hF4DVna4OFrB1pESAQdAC80t7xaXuGWp/b264jhcDV8i3pzs4xD45ynzDc8UI3Yw
      5C1pF1uEUjNJi6V1r8SJQM+0hS8bIHq3W4XB/gM8R+yLh8YstzZpNKEyLlm4v0uN
      0lwB8Lws+OsL0WjwZLBj2hv2hj72R+LlL6iXiL1vOcIKfCvISdPPiZSIS1swvgK0
      2U3kR/HfmZ1GwSHPKwNaCRv7YMvMX5SeZ19Wa5A7dEUXXrXqxkQ3J6NxuzN8rQ==
      =gfgR
      -----END PGP MESSAGE-----
    fp: 9FECE521D41AD3421ACBF4E73AA80B5E13601A29
  unencrypted_suffix: _unencrypted
  version: 3.7.3
