apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tigera-operator
spec:
  chart:
    spec:
      chart: tigera-operator
      sourceRef:
        kind: HelmRepository
        name: tigera-operator
        namespace: tigera-operator
      version: "3.24.3"
  interval: 6h
