apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
  - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 3m
  path: ./apps/demo
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
