apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m
  path: ./infrastructure/demo
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
