apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: cluster-notifications
spec:
  summary: "Test cluster"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
  - kind: GitRepository
    name: '*'
  - kind: HelmRepository
    name: '*'
  - kind: ImageRepository
    name: '*'
  - kind: Kustomization
    name: '*'
  - kind: HelmRelease
    name: '*'
  - kind: HelmChart
    name: '*'
  - kind: ImageUpdateAutomation
    name: '*'
